language: scala
dist: trusty
sudo: required
group: edge
jdk:
  - oraclejdk8
env:
  matrix:
    - SCRIPT=test-code
    - SCRIPT=test-style
# important to use eval, otherwise "&&" is passed as an argument to sbt rather than being processed by bash
script: bin/$SCRIPT
before_install:
    # See https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-239493916
    - rm ~/.m2/settings.xml
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/.m2/repository
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/org.mitre/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/org.mitre/*
  - rm -r $HOME/.m2/repository/org/mitre/*
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.sbt -name "*.lock" -delete
notifications:
  webhooks:
    on_success: always
    on_failure: always
